<a href="https://colab.research.google.com/github/KodumuruRaja/Ensemble-Algorithms/blob/main/Random-Forest%2C%20ADABoost%2C%20Gradient-Tree-Boosting%2C%20Voting-Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
x,y=load_iris(return_X_y=True)

In [ ]:
from sklearn.ensemble import BaggingClassifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
m = KNeighborsClassifier(n_neighbors=3)

In [ ]:
bag = BaggingClassifier(
    m, 
    max_samples=.5, 
    max_features=2, 
    n_jobs=2,
    oob_score=True)

In [ ]:
bag.fit(x, y)

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto',
                                                      leaf_size=30,
                                                      metric='minkowski',
                                                      metric_params=None,
                                                      n_jobs=None,
                                                      n_neighbors=3, p=2,
                                                      weights='uniform'),
                  bootstrap=True, bootstrap_features=False, max_features=2,
                  max_samples=0.5, n_estimators=10, n_jobs=2, oob_score=True,
                  random_state=None, verbose=0, warm_start=False)

In [ ]:
bag.oob_score_

0.9466666666666667

In [ ]:
bag.predict([x[0]])

array([0])

In [ ]:
bag.predict_proba([x[0]])

array([[1., 0., 0.]])

In [ ]:
bag.score(x, y)

0.98

# **Random Forests**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
m = RandomForestClassifier(n_estimators=20, oob_score=True)
m.fit(x,y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
m.predict([x[0]])

array([0])

In [ ]:
m.score(x, y)

1.0

# **ADABOOST**

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
m = AdaBoostClassifier(base_estimator=None, n_estimators=100)
m.fit(x, y)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1.0,
                   n_estimators=100, random_state=None)

In [ ]:
m.score(x, y)

0.9733333333333334

# **Gradient Tree Boosting**

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
m = GradientBoostingClassifier(n_estimators=10)
m.fit(x, y)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=10,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [ ]:
m.score(x,y)

0.9933333333333333

In [ ]:
m.set_params(n_estimators=20, warm_start=True)
m.fit(x, y)
m.score(x, y)

1.0

In [ ]:
m.feature_importances_

array([0.00583056, 0.01038211, 0.24582122, 0.73796611])

# **Voting Classifier**

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [ ]:
m = VotingClassifier(estimators=[('lr', LogisticRegression()), ('rf', RandomForestClassifier()), ('gnb', GaussianNB())], voting='hard')

In [ ]:
m.fit(x,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('rf',
                              RandomForestClassifier(bootstrap=True,
                                                     ccp_alpha=0.0,
                                                     class_weight=None,
                                             

In [ ]:
m.score(x,y)

0.98